<?php
/**
 * OntoWiki image helper module template
 */
$translate = OntoWiki::getInstance()->translate;
$urlBase = OntoWiki::getInstance()->getUrlBase();
?>
<link rel="stylesheet" type="text/css"
      href="<?php echo($urlBase . 'extensions/deadlinehelper/templates/deadlinehelper.css') ?>">

<div class="deadlinehelper">

    <?php if (isset ($this->properties)): ?>
        <div id="accordion">
            <!-- Tabnames of accordion -->
            <?php foreach ($this->properties as $tabname => $dateblocks): ?>
                <h4><?php echo $tabname ?> <?php echo $this->amounts[$tabname] ?></h4>
                <div class="hhh">

                    <!-- the dates for which entries are available -->
                    <?php foreach($dateblocks as $dateKey => $datablock): ?>
                        <div style="font-weight: bold;"><?php echo $dateKey ?>:</div>

                        <!-- the actual entry with name as link -->
                        <?php foreach($datablock as $data): ?>
                            <p style="line-height: 2ex; font-size: 12px;">
                            <a  href="<?php echo $data['subjectUrl'] ?>"> <?php echo $data['subjectTitle'] ?></a>
                            </p>
                            <div style="height: 6px;"></div>
                        <?php endforeach; ?>

                    <?php endforeach; ?>
                </div>
            <?php endforeach; ?>
            <?php foreach ($this->emptytabs as $tabname): ?>
                <h4><?php echo $tabname ?> 0</h4>
                <div class="hhh">
                    <?php echo($translate->translate("No upcoming dates")) ?>
                </div>
            <?php endforeach; ?>
        </div>
        <script>
            $(function () {
                $("#accordion").accordion();
            });
        </script>
    <?php endif ?>

</div>